use std::path::Path;

use crate::error::{HubError, Result};
use crate::git::Git;
use crate::manifest::{MANIFEST_FILE, Manifest};
use crate::names;
use crate::skill;

pub struct InitOptions {
    pub name: Option<String>,
    pub checkout_template: Option<String>,
    /// Refresh the init-owned files of an existing hub instead of failing.
    pub force: bool,
}

const PRE_PUSH_MARKER: &str = "hub coordinator repos are local-only";

const GITIGNORE_LINES: [&str; 5] = [
    ".DS_Store",
    ".tmp/",
    "*.code-workspace",
    ".claude/skills/hub/",
    ".agents/skills/hub/",
];

fn claude_md(name: &str) -> String {
    format!(
        "# {name} hub\n\n\
This directory is a hub coordinator managed by the `hub` CLI. `hub.json` lists the member repos by\n\
role. Each feature's branches, worktrees, and tmux session are recorded on this machine under\n\
`.git/hub/` and are never committed; run `hub status` to see them. Each open feature has its own\n\
worktree of this repo under the configured `worktree_dir`, and a tmux session and worktrees named by\n\
`checkout_template` (default: the feature name).\n\n\
## Rules\n\n\
1. Run `hub status` before acting on any path found in a document. `hub.json` and the hub's own\n   \
records are authoritative; prose is not.\n\
2. Refer to member repos by role, never by filesystem path. Paths differ between machines and\n   \
features.\n\
3. `hub.json` and this branch's documents may be committed and pushed. Feature bindings (branches,\n   \
worktrees, sessions) are local to this machine under `.git/hub/` and are never committed; run\n   \
`hub status` rather than reading files to learn them.\n\
4. Per-repo documentation lives in each repo; this repo only covers how they fit together.\n\
5. The `hub` agent skill in `.claude/skills/hub/` and `.agents/skills/hub/` is generated by the\n   \
`hub` binary on every command; do not edit it.\n"
    )
}

pub fn init(dir: &Path, opts: &InitOptions) -> Result<Vec<String>> {
    if opts.force {
        if opts.name.is_some() || opts.checkout_template.is_some() {
            return Err(HubError::Usage(
                "--force refreshes an existing hub; --name and --checkout-template cannot change it"
                    .into(),
            ));
        }
        if dir.join(MANIFEST_FILE).exists() {
            return refresh(dir);
        }
    }
    let name = match &opts.name {
        Some(name) => name.clone(),
        None => dir
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .ok_or_else(|| {
                HubError::Usage(
                    "cannot derive a hub name from the current directory; pass --name".into(),
                )
            })?,
    };
    names::validate_name("hub name", &name)?;
    if let Some(template) = &opts.checkout_template
        && !names::has_checkout_placeholder(template)
    {
        return Err(HubError::Usage(format!(
            "--checkout-template '{template}' has no placeholder; must contain one of {{feature}}, {{feature_snake}}, {{hub}}"
        )));
    }
    if dir.join(MANIFEST_FILE).exists() {
        return Err(HubError::Precondition(format!(
            "{} is already a hub; rerun with --force to refresh the files hub init owns",
            dir.display()
        )));
    }
    let git = Git::new(dir);
    let mut lines = Vec::new();
    if git.is_repo() {
        require_main(&git, dir)?;
    } else {
        Git::init(dir, "main")?;
        lines.push(format!(
            "Initialized git repository on main in {}",
            dir.display()
        ));
    }
    // Existing user files are never overwritten: CLAUDE.md is kept and
    // .gitignore is merged.

    Manifest::new(&name, opts.checkout_template.as_deref()).save(&dir.join(MANIFEST_FILE))?;
    let mut paths = vec![Path::new(MANIFEST_FILE), Path::new(".gitignore")];
    let claude = dir.join("CLAUDE.md");
    if claude.exists() {
        lines.push("CLAUDE.md exists; left as is".to_string());
    } else {
        write(&claude, &claude_md(&name))?;
        paths.push(Path::new("CLAUDE.md"));
    }
    merge_gitignore(&dir.join(".gitignore"))?;

    git.add(&paths)?;
    git.commit_paths(&format!("hub: init {name}"), &paths)?;
    if let Err(err) = skill::ensure_ignored(&git).and_then(|()| skill::install(dir)) {
        lines.push(format!(
            "warning: {err}; any hub command retries the skill install"
        ));
    }
    lines.push(format!("Created hub '{name}' in {}", dir.display()));
    Ok(lines)
}

fn require_main(git: &Git, dir: &Path) -> Result<()> {
    let branch = git.current_branch()?;
    if branch.as_deref() != Some("main") {
        return Err(HubError::Precondition(format!(
            "{} must be on 'main' to become a hub, found {}",
            dir.display(),
            branch.unwrap_or_else(|| "detached HEAD".into())
        )));
    }
    Ok(())
}

/// Bring the files `hub init` owns up to date in an existing hub: merge the
/// ignore lines, untrack files they now match, remove the pre-push hook a
/// hub before 0.14.0 installed. `hub.json` and `CLAUDE.md` are never touched.
fn refresh(dir: &Path) -> Result<Vec<String>> {
    let git = Git::new(dir);
    require_main(&git, dir)?;

    let mut lines = Vec::new();
    let mut paths: Vec<&Path> = Vec::new();
    if merge_gitignore(&dir.join(".gitignore"))? {
        lines.push("Merged the hub's lines into .gitignore".to_string());
        paths.push(Path::new(".gitignore"));
    }
    let mut untracked: Vec<String> = Vec::new();
    for pattern in GITIGNORE_LINES {
        for file in git.tracked_matching(pattern)? {
            if !untracked.contains(&file) {
                untracked.push(file);
            }
        }
    }
    let untracked_paths: Vec<&Path> = untracked.iter().map(Path::new).collect();
    if !untracked.is_empty() {
        git.rm_cached(&untracked_paths)?;
        lines.extend(untracked.iter().map(|f| format!("Untracked {f}")));
        paths.extend(untracked_paths.iter().copied());
    }
    if !paths.is_empty() {
        if paths.contains(&Path::new(".gitignore")) {
            git.add(&[Path::new(".gitignore")])?;
        }
        commit_without(&git, dir, "hub: refresh init files", &paths, &untracked)?;
    }

    let hook = dir.join(".git").join("hooks").join("pre-push");
    let hub_hook = std::fs::read_to_string(&hook)
        .ok()
        .is_some_and(|t| t.contains(PRE_PUSH_MARKER));
    if hub_hook {
        std::fs::remove_file(&hook)
            .map_err(|e| HubError::io(format!("removing {}", hook.display()), e))?;
        lines.push("Removed .git/hooks/pre-push".to_string());
    }
    if let Err(err) = skill::ensure_ignored(&git).and_then(|()| skill::install(dir)) {
        lines.push(format!(
            "warning: {err}; any hub command retries the skill install"
        ));
    }
    if lines.is_empty() {
        lines.push(format!("Nothing to refresh in {}", dir.display()));
    } else {
        lines.push(format!("Refreshed hub files in {}", dir.display()));
    }
    Ok(lines)
}

/// Commit `paths` while the `absent` files (already removed from the index)
/// are moved aside. `git commit --only` reads the working tree, so a file that
/// is still on disk would otherwise be committed again instead of deleted.
fn commit_without(
    git: &Git,
    dir: &Path,
    message: &str,
    paths: &[&Path],
    absent: &[String],
) -> Result<()> {
    let moved: Vec<(std::path::PathBuf, std::path::PathBuf)> = absent
        .iter()
        .map(|f| (dir.join(f), dir.join(format!("{f}.hub-untracking"))))
        .collect();
    for (from, to) in &moved {
        std::fs::rename(from, to)
            .map_err(|e| HubError::io(format!("moving {} aside", from.display()), e))?;
    }
    let mut result = git.commit_paths(message, paths);
    for (from, to) in &moved {
        if let Err(e) = std::fs::rename(to, from)
            && result.is_ok()
        {
            result = Err(HubError::io(format!("restoring {}", from.display()), e));
        }
    }
    result
}

/// Append the hub's ignore lines that are missing; every existing line is kept.
/// Returns whether the file changed.
fn merge_gitignore(path: &Path) -> Result<bool> {
    let mut text = std::fs::read_to_string(path).unwrap_or_default();
    let mut changed = !path.exists();
    for line in GITIGNORE_LINES {
        if !text.lines().any(|l| l.trim() == line) {
            if !text.is_empty() && !text.ends_with('\n') {
                text.push('\n');
            }
            text.push_str(line);
            text.push('\n');
            changed = true;
        }
    }
    if changed {
        write(path, &text)?;
    }
    Ok(changed)
}

fn write(path: &Path, content: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| HubError::io(format!("creating {}", parent.display()), e))?;
    }
    std::fs::write(path, content)
        .map_err(|e| HubError::io(format!("writing {}", path.display()), e))
}
